name: Push

on:
  push:
    branches:
    - master
  pull_request:
    types:
    - opened
    - synchronize

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Cache
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Setup protoc
      run: |
        curl -sL https://github.com/protocolbuffers/protobuf/releases/download/v3.9.1/protoc-3.9.1-linux-x86_64.zip -o protoc-3.9.1-linux-x86_64.zip
        unzip protoc-3.9.1-linux-x86_64.zip
        sudo cp bin/protoc /usr/local/bin
    - name: Setup gen go
      run: |
        go install github.com/golang/protobuf/protoc-gen-go
        go install github.com/mwitkow/go-proto-validators/protoc-gen-govalidators
    - name: Setup gen doc
      run: |
        curl -sL https://github.com/pseudomuto/protoc-gen-doc/releases/download/v1.4.1/protoc-gen-doc-1.4.1.linux-amd64.go1.15.2.tar.gz -o protoc-gen-doc-1.4.1.linux-amd64.go1.15.2.tar.gz
        tar xvzf protoc-gen-doc-1.4.1.linux-amd64.go1.15.2.tar.gz
        sudo cp protoc-gen-doc-1.4.1.linux-amd64.go1.15.2/protoc-gen-doc /usr/local/bin
    - name: Setup vendor
      run: |
        git clone --depth 1 https://github.com/protocolbuffers/protobuf vendor/github.com/protocolbuffers/protobuf
        git clone --depth 1 https://github.com/mwitkow/go-proto-validators vendor/github.com/mwitkow/go-proto-validators
        git clone --depth 1 https://github.com/googleapis/googleapis vendor/github.com/googleapis/googleapis
    - name: Generate
      run: |
        make build
        make build-protoset
    - name: Add
      id: add
      continue-on-error: true
      run: |
        git add sample
        git diff --cached --exit-code
    - name: Push
      if: github.event_name == 'push' && steps.add.outcome != 'success'
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git commit --author "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>" -m 'Automatically update sample'
        git push origin master
